
import React, { useState } from 'react';
import { Mail } from 'lucide-react';
import { Language } from '../types';
import { TRANSLATIONS } from '../constants';
import { AnimatePresence } from 'framer-motion';
import { InfoModal } from './InfoModal';

interface FooterProps {
    language: Language;
}

export const Footer: React.FC<FooterProps> = ({ language }) => {
  const t = TRANSLATIONS[language];
  const [activeModal, setActiveModal] = useState<{ title: string, content: React.ReactNode } | null>(null);

  const modalContents: Record<string, React.ReactNode> = {
    about: (
        <>
            <p><strong>ScoopNewspaper</strong> is a futuristic, AI-powered news experience designed to bring the tactile joy of reading a physical newspaper into the digital age.</p>
            <p>Utilizing advanced WebGL technology for our 3D view and Google's Gemini AI for real-time content generation, we aim to provide an immersive reading environment that adapts to your interests and language.</p>
        </>
    ),
    contact: (
        <>
            <p>We'd love to hear from you!</p>
            <p className="mt-4"><strong>Email:</strong><br/>contact@scoopnewspaper.com</p>
            <p><strong>Press Inquiries:</strong><br/>press@scoopnewspaper.com</p>
            <p><strong>Address:</strong><br/>123 Innovation Dr, Tech City, TC 90210</p>
        </>
    ),
    privacy: (
        <>
            <p>Your privacy is critically important to us.</p>
            <ul className="list-disc pl-4 space-y-2 mt-2">
                <li>We do not track your personal reading history.</li>
                <li>We do not sell your data to third parties.</li>
                <li>All AI generation happens anonymously.</li>
                <li>Cookies are used solely for saving your language and layout preferences.</li>
            </ul>
        </>
    ),
    terms: (
        <>
            <p>By using ScoopNewspaper, you agree to the following terms:</p>
            <p>The content generated by AI is for entertainment and informational purposes. While we strive for accuracy, we verify real-world news via external APIs where possible. Always verify critical information with primary sources.</p>
        </>
    )
  };

  const links = [
      { key: 'about', label: t.about },
      { key: 'contact', label: t.contact },
      { key: 'privacy', label: t.privacy },
      { key: 'terms', label: t.terms },
  ];

  return (
    <>
      <footer className="w-full h-auto py-4 md:h-16 bg-[#0a0a0a] border-t border-white/5 flex flex-col md:flex-row items-center justify-between px-6 text-[10px] md:text-xs text-gray-500 z-50 shrink-0 gap-4 md:gap-0">
        
        {/* Links Section */}
        <div className="flex flex-wrap justify-center md:justify-start gap-x-4 gap-y-2 flex-1">
          {links.map((link, index) => (
            <React.Fragment key={link.key}>
                <button 
                    onClick={() => setActiveModal({ title: link.label, content: modalContents[link.key] })}
                    className="hover:text-blue-400 transition-colors whitespace-nowrap"
                >
                    {link.label}
                </button>
                {index < links.length - 1 && (
                    <span className="hidden md:inline text-gray-700">|</span>
                )}
            </React.Fragment>
          ))}
        </div>

        {/* Copyright & Credits */}
        <div className="text-center flex flex-col items-center md:items-end gap-1 opacity-70">
          <p>© 2025 ScoopNewspaper. All rights reserved.</p>
          <p className="flex gap-1">
             Designer & Developer by <a href="https://codeenergy.org" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:text-blue-400 font-bold">Code Energy</a>
          </p>
        </div>

        {/* Message Action */}
        <div className="flex gap-4 items-center md:ml-8">
           <a 
              href="mailto:contact@scoopnewspaper.com"
              className="flex items-center gap-2 px-3 py-1.5 bg-white/5 hover:bg-white/10 border border-white/10 rounded-lg transition-colors text-gray-300 hover:text-white"
           >
              <Mail size={14} />
              <span>Send Message</span>
           </a>
        </div>

      </footer>

      <AnimatePresence>
        {activeModal && (
            <InfoModal 
                title={activeModal.title} 
                content={activeModal.content} 
                onClose={() => setActiveModal(null)} 
            />
        )}
      </AnimatePresence>
    </>
  );
};
